CREATE DATABASE ossinsight_share DEFAULT COLLATE utf8mb4_general_ci;

CREATE TABLE share_data
(
    `id`          CHAR(36) CHARACTER SET ascii      NOT NULL COMMENT 'Share ID, uuid v4 generated by client',
    `title`       VARCHAR(255)                      NOT NULL COMMENT 'Content for <title>',
    `description` VARCHAR(255)                      NOT NULL COMMENT 'Content for <meta name=description>',
    `keyword`     VARCHAR(255)                      NOT NULL COMMENT 'Content for <meta name=keyword>',
    `image_url`   VARCHAR(255) CHARACTER SET ascii  NOT NULL COMMENT 'Default image url',
    `path`        VARCHAR(2083) CHARACTER SET ascii NOT NULL COMMENT 'Real url path (includes hash and querystring)',
    `meta`        JSON                              NOT NULL COMMENT 'Meta info',
    `created_at`  DATETIME                          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `session_id`  CHAR(32) CHARACTER SET ascii      NOT NULL COMMENT 'Session ID generated by client IP',
    INDEX share_data_idx_path (`path`),
    INDEX share_data_idx_session_id (`session_id`)
);
